# Generated by Django 3.0.7 on 2020-07-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoria del Local',
                'verbose_name_plural': 'Categorias de los Locales',
            },
        ),
        migrations.CreateModel(
            name='CentroComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Centro Comercial',
                'verbose_name_plural': 'Centros Comerciales',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categoria_local', models.ManyToManyField(related_name='categoria_local', to='centro_comercial.CategoriaLocal', verbose_name='Categorias del Local')),
                ('centro_comercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales_centro_comercial', to='centro_comercial.CentroComercial', verbose_name='Centro Comercial')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
    ]
