# Generated by Django 3.0.7 on 2020-07-02 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=15)),
                ('estadoCivil', models.CharField(choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], default='soltero', max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('direccion', models.TextField(default='Dirección', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('fechaApertura', models.DateField(auto_now_add=True)),
                ('tipoCuenta', models.CharField(choices=[('ahorros', 'Ahorros'), ('corriente', 'Corriente'), ('programado', 'Programado')], default='ahorros', max_length=30)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('estado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Trasaccion',
            fields=[
                ('transaccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField(default='descripción de la transacción')),
                ('responsable', models.CharField(max_length=100)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelo.Cuenta')),
            ],
        ),
    ]
