# Generated by Django 3.0.7 on 2020-07-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=225)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=200)),
            ],
        ),
    ]
