# Generated by Django 3.0.7 on 2020-07-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_banco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trasaccion',
            new_name='Transaccion',
        ),
    ]
