# Generated by Django 3.0.7 on 2020-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20200715_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
