# Generated by Django 3.0.7 on 2020-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0004_cliente_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
